AWSTemplateFormatVersion: 2010-09-09

Description: The AWS CloudFormation template that creates the CodePipeline 
  Cross Account Role that will be assumed by the tooling account (DEV) to
  deploy into target accounts (BETA, PROD, etc.)

Parameters:
  ToolsAccountId:
    Type: String
    Description: Account ID of the tooling AWS Account that initiates deployments to this account.
    ConstraintDescription: Must be a valid AWS Account ID without hyphens.
    AllowedPattern: '\d{12}'
    MinLength: 12
    MaxLength: 12
  Stage:
    Type: String
    Description: Stage of the account we're deploying to.
    AllowedValues:
      - Beta
      - Prod
  KeyArn:
    Description: Provide the ARN of the KMS Key used to encrypt the S3 artifact bucket in the tooling account (DEV).
    Type: String
    ConstraintDescription: Must be a valid AWS ARN for a KMS Key in the tooling account (DEV).
    MinLength: 1

Resources:
  CrossAccountDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineCrossAccountRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          # TRUST POLICY: Allows any IAM principal (users/roles) in the Tooling account
          # to assume this role. This is the foundation of cross-account access,
          # enabling CodePipeline in the Tooling account to perform deployments
          # in this target account by assuming this role via STS.
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${ToolsAccountId}:root
            Action:
              - sts:AssumeRole
  # CrossAccountDeploymentPolicy:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties:
  #     Description: Allows pipeline in tooling account to deploy CloudFormation resources into the target account through assumed CodePipelineCrossAccountRole.
  #     ManagedPolicyName: CodePipelineCrossAccountPolicy
  #     Roles:
  #       - !Ref CrossAccountDeploymentRole
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
          # Permissions to initiate CloudFormation stack operations,
          # Flow: This role calls CloudFormation API (knocking on the door)
          #   -> This role passes the CloudFormationDeploymentRole to CloudFormation service
          #   -> CloudFormation service calls the API.
          # - Effect: Allow
          #   Action:
          #     - cloudformation:CreateStack
          #     - cloudformation:GetTemplate
          #     - cloudformation:ValidateTemplate
          #     - cloudformation:DeleteStack
          #     - cloudformation:UpdateStack
          #     - cloudformation:DescribeStack*
          #   Resource: "*"
          # IAM PASS ROLE: Allows CodePipeline to pass the CloudFormationDeploymentRole
          # to CloudFormation when creating/updating stacks. This is required because
          # CloudFormation needs an execution role to create resources on behalf of
          # the pipeline. Without this permission, CloudFormation cannot assume the
          # role needed to provision resources like Lambda functions and API Gateway.
          # - Effect: Allow
          #   Action:
          #     - iam:PassRole
          #   Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/CloudFormationDeploymentRole
          # S3 ARTIFACT ACCESS: Allows reading and writing deployment artifacts
          # (e.g., CloudFormation templates, Lambda code packages) from the shared
          # artifact bucket in the Tools account. CodePipeline stores build outputs
          # here, and CloudFormation needs to retrieve them during deployment.
          # ListBucket is needed to check for object existence.
          # - Effect: Allow
          #   Action:
          #     - s3:Get*
          #     - s3:Put*
          #     - s3:ListBucket
            # Resource: "*"  # TODO: limit to the S3 bucket used by the pipeline
          # CloudFormationDeploymentRole needs KMS permissions to read/decrypt the templates in the S3 bucket,
          # CloudPipelineCrossAccountRole needs KMS permissions to prove the templates are ready to be deployed.
          # - Effect: Allow
          #   Action:
          #     - kms:DescribeKey
          #     - kms:GenerateDataKey*
          #     - kms:Encrypt
          #     - kms:ReEncrypt*
          #     - kms:Decrypt
          #   Resource: !Sub ${KeyArn}
